apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkoutservice
  namespace: argocd
spec:
  project: boutique
  source:
    repoURL: 'http://192.168.0.104/devops/Boutique-charts.git'
    targetRevision: main
    path: checkoutservice
    helm:
      releaseName: checkoutservice
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
